[tool.poetry]
name = "omoide"
version = "0.2.0"
description = "Simple image storing application"
authors = ["IgorZyktin <nicord@yandex.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
psycopg2 = "^2.9.3"
fastapi = "^0.85.1"
uvicorn = "^0.18.2"
Jinja2 = "^3.0.3"
python-multipart = "^0.0.5"
databases = "^0.5.3"
asyncpg = "^0.25.0"
bcrypt = "^3.2.0"
SQLAlchemy = {extras = ["mypy"], version = "^1.4.35"}
click = "^8.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
coverage = "^6.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
