[tool.poetry]
name = "omoide"
version = "0.2.0"
description = "Simple image storing application"
authors = ["IgorZyktin <nicord@yandex.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
psycopg2 = "^2.9.5"
fastapi = "^0.89.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
Jinja2 = "^3.0.3"
python-multipart = "^0.0.5"
databases = "^0.7.0"
asyncpg = "^0.27.0"
bcrypt = "^4.0.1"
SQLAlchemy = "^1.4.45"
click = "^8.1.2"
ujson = "^5.5.0"
loguru = "^0.6.0"
gunicorn = "^20.1.0"
prettytable = "^3.5.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
coverage = "^6.5"
pytest-asyncio = "^0.20.1"
mypy = "^1.1"
sqlalchemy2-stubs = "^0.0.2-alpha.29"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
