"""Sync.

Revision ID: ffeecde84b84
Revises: 84e7c23cac48
Create Date: 2026-07-07 23:04:04.703414+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'ffeecde84b84'
down_revision: str | None = '84e7c23cac48'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Adding stuff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('command_queue_parallel', 'log', existing_type=sa.TEXT(), nullable=False)
    op.drop_index(op.f('ix_command_queue_parallel_name'), table_name='command_queue_parallel')
    op.create_index(
        op.f('ix_command_queue_parallel_requested_by'),
        'command_queue_parallel',
        ['requested_by'],
        unique=False,
    )
    op.drop_constraint(
        op.f('command_queue_parallel_requested_by_fkey'),
        'command_queue_parallel',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None, 'command_queue_parallel', 'users', ['requested_by'], ['id'], ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Removing stuff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'command_queue_parallel', type_='foreignkey')
    op.create_foreign_key(
        op.f('command_queue_parallel_requested_by_fkey'),
        'command_queue_parallel',
        'users',
        ['requested_by'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_index(
        op.f('ix_command_queue_parallel_requested_by'), table_name='command_queue_parallel'
    )
    op.create_index(
        op.f('ix_command_queue_parallel_name'), 'command_queue_parallel', ['name'], unique=False
    )
    op.alter_column('command_queue_parallel', 'log', existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
