"""Updated migrations.

Revision ID: d4d6001bb918
Revises: 8870dd74f3df
Create Date: 2026-02-20 21:56:35.308086+03:00
"""

from typing import Sequence

from alembic import op


revision: str = 'd4d6001bb918'
down_revision: str | None = '8870dd74f3df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Adding stuff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_parent_uuid_fkey'), 'items', type_='foreignkey')
    op.drop_constraint(op.f('items_owner_uuid_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'items', ['parent_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'items', 'users', ['owner_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Removing stuff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_owner_uuid_fkey'), 'items', 'users', ['owner_uuid'], ['uuid'])
    op.create_foreign_key(
        op.f('items_parent_uuid_fkey'), 'items', 'items', ['parent_uuid'], ['uuid']
    )
    # ### end Alembic commands ###
