"""Change content size to bigint

Revision ID: 8ca57ddc101c
Revises: b0ba5b2255db
Create Date: 2026-03-04 22:52:39.921191+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '8ca57ddc101c'
down_revision: str | None = 'b0ba5b2255db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Adding stuff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'item_metainfo',
        'content_size',
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Removing stuff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'item_metainfo',
        'content_size',
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
