"""Added media queues

Revision ID: b0ba5b2255db
Revises: d4d6001bb918
Create Date: 2026-02-20 22:06:19.606961+03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'b0ba5b2255db'
down_revision: str | None = 'd4d6001bb918'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Adding stuff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'queue_input_media',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_uuid', sa.UUID(), nullable=False),
        sa.Column('item_uuid', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('lock', sa.String(length=64), nullable=True),
        sa.Column('ext', sa.String(length=64), nullable=False),
        sa.Column('content_type', sa.String(length=256), nullable=False),
        sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('content', postgresql.BYTEA(), nullable=False),
        sa.ForeignKeyConstraint(['item_uuid'], ['items.uuid'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_queue_input_media_created_at'), 'queue_input_media', ['created_at'], unique=False
    )
    op.create_index(op.f('ix_queue_input_media_id'), 'queue_input_media', ['id'], unique=True)
    op.create_index(
        op.f('ix_queue_input_media_item_uuid'), 'queue_input_media', ['item_uuid'], unique=False
    )
    op.create_index(
        op.f('ix_queue_input_media_user_uuid'), 'queue_input_media', ['user_uuid'], unique=False
    )
    op.create_table(
        'queue_output_media',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_uuid', sa.UUID(), nullable=False),
        sa.Column('item_uuid', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('lock', sa.String(length=64), nullable=True),
        sa.Column('ext', sa.String(length=64), nullable=False),
        sa.Column('content_type', sa.String(length=256), nullable=False),
        sa.Column('media_type', sa.String(length=64), nullable=False),
        sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('content', postgresql.BYTEA(), nullable=False),
        sa.Column('processed_by', postgresql.ARRAY(sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(['item_uuid'], ['items.uuid'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_queue_output_media_created_at'), 'queue_output_media', ['created_at'], unique=False
    )
    op.create_index(op.f('ix_queue_output_media_id'), 'queue_output_media', ['id'], unique=True)
    op.create_index(
        op.f('ix_queue_output_media_item_uuid'), 'queue_output_media', ['item_uuid'], unique=False
    )
    op.create_index(
        op.f('ix_queue_output_media_user_uuid'), 'queue_output_media', ['user_uuid'], unique=False
    )
    # ### end Alembic commands ###

    op.execute('GRANT ALL ON queue_input_media TO omoide_app;')
    op.execute('GRANT ALL ON queue_input_media TO omoide_worker;')
    op.execute('GRANT SELECT ON queue_input_media TO omoide_monitoring;')

    op.execute('GRANT ALL ON queue_output_media TO omoide_app;')
    op.execute('GRANT ALL ON queue_output_media TO omoide_worker;')
    op.execute('GRANT SELECT ON queue_output_media TO omoide_monitoring;')


def downgrade() -> None:
    """Removing stuff."""
    op.execute('REVOKE ALL PRIVILEGES ON queue_input_media FROM omoide_app;')
    op.execute('REVOKE ALL PRIVILEGES ON queue_input_media FROM omoide_worker;')
    op.execute('REVOKE ALL PRIVILEGES ON queue_input_media FROM omoide_monitoring;')

    op.execute('REVOKE ALL PRIVILEGES ON queue_output_media FROM omoide_app;')
    op.execute('REVOKE ALL PRIVILEGES ON queue_output_media FROM omoide_worker;')
    op.execute('REVOKE ALL PRIVILEGES ON queue_output_media FROM omoide_monitoring;')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_output_media_user_uuid'), table_name='queue_output_media')
    op.drop_index(op.f('ix_queue_output_media_item_uuid'), table_name='queue_output_media')
    op.drop_index(op.f('ix_queue_output_media_id'), table_name='queue_output_media')
    op.drop_index(op.f('ix_queue_output_media_created_at'), table_name='queue_output_media')
    op.drop_table('queue_output_media')
    op.drop_index(op.f('ix_queue_input_media_user_uuid'), table_name='queue_input_media')
    op.drop_index(op.f('ix_queue_input_media_item_uuid'), table_name='queue_input_media')
    op.drop_index(op.f('ix_queue_input_media_id'), table_name='queue_input_media')
    op.drop_index(op.f('ix_queue_input_media_created_at'), table_name='queue_input_media')
    op.drop_table('queue_input_media')
    # ### end Alembic commands ###
