name: Omoide
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install poetry
          poetry install
          poetry install --dev
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Lint with Ruff
        run: ruff check --output-format=github .

      - name: Test with mypy
        run: mypy ./omoide

      - name: Test with pytest
        run: pytest ./omoide/tests/
